[package]
name = "nasa-api"
version = "0.1.0"
authors = ["Cyprien"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["web", "router"] }
serde = { version = "1.0.210", features = ["derive"] }
# Debug
dioxus-logger = "0.5.1"
reqwest = { version = "0.12.7", features = ["json"] }
regex = "1.10.6"
scraper = "0.21.0"
getrandom = { version = "0.2.15", features = ["js"] }
log = "0.4.22"
serde_json = "1.0.124"
rand = "0.8.5"
wasm-bindgen = "0.2.92"
dotenv = "0.15.0"
freyr = "0.1.5"

[build-dependencies]
dotenv = "0.15"

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
