[package]
name = "dioxusproject"
version = "0.1.0"
authors = ["Cyprien <cbdefontenay@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }

dioxus = { version = "0.5", features = ["fullstack", "router"] }

# Debug
dioxus-logger = "0.5.1"
reqwest = "0.12.5"
regex = "1.10.6"
manganis = "0.2.2"
scraper = "0.20.0"
getrandom = { version = "0.2.15", features = ["js"] }
log = "0.4.22"

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
