[build]
command = "cargo build"

[build.environment]
RUST_VERSION = "stable"
RUSTUP_HOME = "/opt/buildhome/.rustup"
CARGO_HOME = "/opt/buildhome/.cargo"

[[plugins]]
package = "@netlify/plugin-rust"

[context.production]
environment = { "RUST_VERSION" = "stable" }
