pub(crate) mod about_component;
pub(crate) mod home_component;
pub(crate) mod nav_bar_component;
pub(crate) mod posts_component;
pub(crate) mod mars_mission_component;
pub(crate) mod header_component;
pub(crate) mod env;
pub(crate) mod sun_component;
pub(crate) mod mars_explanation_component;
pub(crate) mod planets_component;
mod card_component;